#!/bin/bash
set -e
source all_installer_list.sh
check_root
#-----------First part-----------------
UNINSTALL_WILD
ADD_FASTESTMIRROR
ENABLE_3RDPARTY_REPOS
ENABLE_FLATHUB
INSTALL_FONTS
#INSTALL_STARSHIP
INSTALL_SYNTHSHELL
INSTALL_PFETCH
INSTALL_ST4
INSTALL_CODIUM
UPDATE_AND_REBOOT

#----------Second part-------------------------
#-------------Flatpaks and Software-----------#
INSTALL_NEOVIM
INSTALL_TMUX
#--------------------
INSTALL_BLEACHBIT
INSTALL_VARIETY
INSTALL_QBITTORRENT
INSTALL_VLC
INSTALL_CALIBRE
#-------------------------
INSTALL_LIBREWOLF_FLATPAK
INSTALL_CHROMIUM_FLATPAK
INSTALL_FOLIATE_FLATPAK
INSTALL_KEEPASSXC_FLATPAK
INSTALL_BITWARDEN_FLATPAK
INSTALL_TORBROWSER_FLATPAK
INSTALL_SIGNAL_FLATPAK
INSTALL_TELEGRAM_FLATPAK
INSTALL_JOPLIN_FLATPAK
INSTALL_SHORTWAVE_FLATPAK
